BASE58_CHARS = set("123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz")
UPPERCASE_BASE58 = set("ABCDEFGHJKLMNPQRSTUVWXYZ")

COOL_WORDS = [
    "ace", "ape", "arc", "art", "axe",
    "bad", "bag", "ban", "bar", "bat", "bay", "bed", "bet", "big", "bit",
    "bob", "bog", "bot", "bow", "box", "boy", "bud", "bug", "bum", "bun",
    "bus", "but", "buy",
    "cab", "cad", "cam", "can", "cap", "car", "cat", "cop", "cow", "cry",
    "cub", "cud", "cup", "cur", "cut",
    "dab", "dad", "dam", "day", "den", "dew", "did", "dig", "dim", "dip",
    "doc", "dog", "don", "dot", "dry", "dub", "dud", "dug", "dun", "duo",
    "dye",
    "ear", "eat", "eel", "egg", "ego", "end", "era", "eve", "ewe", "eye",
    "fab", "fad", "fan", "far", "fat", "fax", "fed", "fee", "fen", "few",
    "fig", "fin", "fir", "fit", "fix", "fly", "foe", "fog", "fop", "for",
    "fox", "fry", "fun", "fur",
    "gab", "gag", "gap", "gas", "gay", "gem", "get", "gig",
    "gin", "gnu", "god", "got", "gum", "gun", "gut", "guy", "gym",
    "had", "hag", "ham", "has", "hat", "hay", "hen", "her", "hew", "hex",
    "hid", "him", "hip", "his", "hit", "hob", "hod", "hog", "hop", "hot",
    "how", "hub", "hue", "hug", "hum", "hut",
    "ice", "icy", "imp", "ink", "inn", "ion", "ire", "irk", "ivy",
    "jab", "jag", "jam", "jar", "jaw", "jay", "jet", "jig", "job", "jog",
    "jot", "joy", "jug", "jut",
    "keg", "ken", "key", "kid", "kin", "kit",
    "lab", "lad", "lag", "lap", "law", "lay", "lea", "led", "leg", "let",
    "lid", "lip", "lit", "log", "lot", "low", "lug",
    "mad", "man", "map", "mar", "mat", "maw", "max", "may", "men", "met",
    "mid", "mix", "mob", "mod", "mom", "mop", "mow", "mud", "mug", "mum",
    "nab", "nag", "nap", "net", "new", "nib", "nit", "nod", "nor", "not",
    "now", "nub", "nun", "nut",
    "oak", "oar", "oat", "odd", "ode", "opt", "orb", "ore", "our", "out",
    "owe", "own",
    "pad", "pan", "paw", "pay", "pea", "peg", "pen", "pep", "per", "pet",
    "pew", "pie", "pig", "pin", "pit", "pod", "pop", "pot", "pow", "pro",
    "pry", "pub", "pug", "pun", "pup", "pus", "put",
    "rag", "ram", "ran", "rap", "rat", "raw", "ray", "red", "ref", "rev",
    "rib", "rid", "rig", "rim", "rip", "rob", "rod", "roe", "rot", "row",
    "rub", "rug", "rum", "run", "rut", "rye",
    "sac", "sad", "sag", "sap", "sat", "saw", "say", "sea", "set", "sew",
    "shy", "sin", "sip", "sir", "sis", "sit", "six", "ski", "sky", "sly",
    "sob", "sod", "son", "sop", "sot", "sow", "soy", "spa", "spy", "sty",
    "sub", "sue", "sum", "sun", "sup",
    "tab", "tad", "tag", "tan", "tap", "tar", "tat", "tax", "tea", "ten",
    "the", "tie", "tin", "tip", "toe", "ton", "too", "top", "tot", "tow",
    "toy", "try", "tub", "tug", "two",
    "urn", "use",
    "van", "vat", "vet", "vex", "via", "vie", "vim", "vow",
    "wad", "wag", "war", "was", "wax", "way", "web", "wed", "wet", "who",
    "why", "wig", "win", "wit", "woe", "wok", "won", "woo", "wow",
    "yak", "yam", "yap", "yaw", "yea", "yes", "yet", "yew",
    "zap", "zed", "zen", "zig", "zip", "zoo",
    "able", "acid", "aged", "area", "army", "auto", "away",
    "baby", "back", "bake", "band", "bang", "bank", "bare", "bark", "barn",
    "base", "bass", "bath", "bead", "beam", "bean", "bear", "beat", "beef",
    "beer", "bend", "best", "bike", "bind", "bird", "bite", "boar", "boat",
    "body", "bomb", "bond", "bone", "book", "boom", "boot", "born", "boss",
    "bout", "brave", "brew", "buck", "buff", "bulk", "bump", "burn", "bust",
    "cafe", "cage", "cake", "calm", "came", "camp", "cape", "card", "care",
    "cart", "case", "cash", "cast", "cave", "chip", "chop", "cite", "city",
    "clan", "claw", "clay", "clip", "club", "clue", "coat", "code", "coil",
    "coin", "coke", "cold", "come", "cook", "cool", "cope", "copy", "cord",
    "core", "corn", "cost", "coup", "crew", "crop", "crow", "cube", "cult",
    "curb", "cure", "cute",
    "damn", "dare", "dark", "dart", "dash", "data", "dawn", "dead", "deaf",
    "deal", "dear", "debt", "deck", "deed", "deem", "deep", "deer", "demo",
    "deny", "desk", "dice", "diet", "dirt", "disc", "dish", "dock", "doge",
    "dome", "done", "doom", "door", "dose", "down", "drab", "drag", "draw",
    "drew", "drip", "drop", "drum", "duck", "dude", "duke", "dumb", "dump",
    "dune", "dung", "dunk", "dusk", "dust", "duty",
    "each", "earn", "ease", "east", "easy", "edge", "edit", "epic",
    "euro", "even", "ever", "exam", "exit", "expo", "eyed", "eyes",
    "face", "fact", "fade", "fain", "fair", "fake", "fall", "fame", "fang",
    "fare", "farm", "fast", "fate", "fear", "feat", "feed", "feel", "fees",
    "fell", "felt", "fern", "fest", "file", "film", "find", "fine", "fire",
    "firm", "fish", "fist", "five", "flag", "flat", "flaw", "fled", "flip",
    "flog", "flow", "foam", "foes", "foil", "fold", "folk", "fond", "font",
    "food", "fool", "foot", "ford", "fork", "form", "fort", "foul", "four",
    "free", "frog", "from", "fuel", "full", "fume", "fund", "fury", "fuse",
    "gain", "gait", "gale", "game", "gang", "garb", "gate",
    "gave", "gaze", "gear", "gene", "gift", "gist", "give", "glad", "glow",
    "glue", "goat", "goes", "gold", "golf", "gone", "good", "grab", "gray",
    "grew", "grid", "grim", "grin", "grip", "grit", "grow",
    "hack", "hail", "hair", "hake", "half", "halt", "hand", "hang", "hard",
    "hare", "harm", "harp", "hash", "hate", "haul", "have", "hawk", "haze",
    "head", "heap", "hear", "heat", "heed", "heel", "heir", "held", "helm",
    "help", "herb", "herd", "here", "hero", "hide", "high", "hike", "hill",
    "hint", "hire", "hold", "hole", "holy", "home", "hood", "hook", "hope",
    "horn", "host", "huge", "hull", "hump", "hung", "hunt", "hurt",
    "icon", "idea", "idle",
    "jack", "jade", "jaws", "jazz", "jedi", "jest", "join", "joke",
    "jump", "junk", "jury", "just",
    "keen", "keep", "kept", "kick", "kill", "kind", "king", "kiss", "knee",
    "knew", "knit", "knob", "knot", "know",
    "lace", "lack", "laid", "lair", "lake", "lamb", "lame", "lamp", "land",
    "lane", "lark", "lash", "lass", "last", "late", "lava", "lawn", "lead",
    "leaf", "lean", "leap", "left", "lend", "lens", "less", "lied", "life",
    "lift", "like", "limb", "lime", "limp", "line", "link", "lion", "list",
    "live", "load", "loaf", "loan", "lock", "loft", "lone", "long", "look",
    "loop", "lord", "lore", "lose", "loss", "lost", "loud", "love", "luck",
    "lump", "lung", "lure", "lurk", "lush", "lust",
    "mace", "made", "mail", "main", "make", "male", "malt", "mane", "many",
    "mare", "mark", "mars", "mart", "mash", "mask", "mass", "mate", "maze",
    "meal", "mean", "meat", "meet", "meld", "melt", "memo", "mend", "menu",
    "mere", "mesh", "mess", "mild", "mile", "milk", "mill", "mind", "mine",
    "mint", "miss", "mist", "mock", "mode", "mold", "monk", "mood", "moon",
    "more", "moss", "most", "moth", "move", "much", "mule", "muse", "must",
    "myth",
    "nail", "name", "navy", "near", "neat", "neck", "need", "nest", "news",
    "next", "nice", "nine", "node", "none", "norm", "nose", "note", "noun",
    "amid", "apex", "atom", "avid", "axle",
    "bold", "bolt", "bred", "bulb", "burp",
    "chad", "char", "chin", "clad", "clog", "coal", "colt", "comb", "cone",
    "cork", "crab", "cram", "crib", "curl",
    "daft", "damp", "daze", "deft", "dent",
    "etch", "evil",
    "fawn", "feat", "fend", "feud", "fizz", "flex", "flop", "flux",
    "gawk", "germ", "gild", "glen", "glob", "gong", "grit", "gulp",
    "helm", "hive", "hoof", "howl",
    "iota",
    "java", "jinx", "jolt",
    "kelp", "kite",
    "lava", "limn", "lynx",
    "mast", "meek", "mesa", "mink", "moat", "molt", "moot", "murk", "musk",
    "nerd", "newt", "nook", "nova", "numb",
    "oink", "omen", "onyx", "opal", "orca",
    "pack", "palm", "pact", "pane", "papa", "park", "part", "pass", "past",
    "path", "pave", "peak", "pear", "peck", "peel", "peer", "pelt", "pick",
    "pier", "pike", "pile", "pine", "pink", "pipe", "plan", "play", "plea",
    "plot", "ploy", "plug", "plum", "plus", "poem", "poet", "poke", "poll",
    "polo", "pond", "pony", "pool", "poor", "pore", "pork", "port", "pose",
    "post", "pour", "pray", "prey", "prop", "prow", "pull", "pulp", "pump",
    "punk", "pure", "push",
    "quay",
    "race", "rack", "raft", "rage", "raid", "rail", "rain", "rake", "ramp",
    "rang", "rank", "rare", "rash", "rate", "rave", "read", "real", "reap",
    "rear", "reed", "reef", "rein", "rely", "rent", "rest", "rice", "rich",
    "ride", "rift", "ring", "riot", "rise", "risk", "road", "roam", "roar",
    "robe", "rock", "rode", "role", "roll", "roof", "room", "root", "rope",
    "rose", "ruin", "rule", "rung", "rush", "rust",
    "safe", "sage", "said", "sail", "sake", "salt", "same", "sand", "sang",
    "save", "scan", "scar", "seal", "seed", "seek", "seem", "seen", "self",
    "sell", "send", "sept", "shed", "shin", "ship", "shoe", "shop", "shot",
    "show", "shut", "sick", "side", "sift", "sign", "silk", "sink", "site",
    "size", "skin", "skip", "slam", "slap", "slim", "slip", "slot", "slow",
    "slug", "snap", "snow", "soak", "soar", "sock", "sofa", "soft", "soil",
    "sold", "sole", "solo", "some", "song", "soon", "sort", "soul", "sour",
    "span", "spar", "spec", "spin", "spit", "spot", "star", "stay", "stem",
    "step", "stew", "stir", "stop", "stub", "stud", "such", "suit", "sung",
    "sure", "surf", "swan", "swap", "swim",
    "tack", "tact", "tail", "take", "tale", "talk", "tall", "tame", "tang",
    "tank", "tape", "task", "taxi", "team", "tear", "tell", "tend", "tent",
    "term", "test", "text", "than", "that", "them", "then", "they", "thin",
    "this", "thus", "tick", "tide", "tidy", "tier", "tile", "till", "time",
    "tiny", "tire", "toad", "told", "toll", "tomb", "tone", "took", "tool",
    "tops", "torn", "toss", "tour", "town", "trap", "tray", "tree", "trek",
    "trim", "trip", "true", "tube", "tuck", "tuft", "tune", "turf", "turn",
    "tusk", "twin", "type",
    "ugly", "undo", "unit", "upon", "used", "user",
    "vale", "vane", "vary", "vast", "veil", "vein", "vent", "verb", "very",
    "vest", "view", "vine", "void", "volt", "vote",
    "wade", "wage", "wait", "wake", "walk", "wall", "wand", "want", "ward",
    "warm", "warn", "warp", "wart", "wash", "wave", "weak", "wear", "weed",
    "week", "were", "west", "what", "when", "whim", "whip", "whom", "wick",
    "wide", "wife", "wild", "will", "wilt", "wind", "wine", "wing", "wink",
    "wipe", "wire", "wise", "wish", "with", "woke", "wolf", "wood", "wool",
    "word", "wore", "work", "worm", "worn", "wrap", "wren",
    "yank", "yard", "yarn", "year", "yell", "yoga", "yoke",
    "zeal", "zero", "zinc", "zone", "zoom",
    "amber", "angel", "armor", "arrow", "beast",
    "blade", "blaze", "bloom", "brain", "brave",
    "chaos", "charm", "chase", "chief", "cider", "claim",
    "cobra", "coral", "craft", "crane", "crash", "cream",
    "crest", "crown", "crush", "crypt", "cyber",
    "dance", "death", "demon", "devil", "dingo",
    "draft", "drain", "drake", "dream", "drift",
    "drive", "droid", "dwarf",
    "eager", "eagle", "earth", "ember",
    "fable", "fairy", "faith", "feast", "fiber", "field",
    "fiery", "fight", "final", "first", "flame", "flash",
    "flesh", "flint", "flood", "forge", "forte", "frost",
    "ghost", "giant", "gleam", "glide", "globe", "glory",
    "golem", "grace", "grain", "grand", "grape", "grasp",
    "greed", "green", "grind", "guard", "guide", "guild",
    "haven", "heart", "hound", "hyper",
    "ivory",
    "jewel", "joker",
    "karma", "knife", "knack",
    "light", "lunar", "lyric",
    "magic", "maple", "marsh", "medal", "mercy", "might",
    "miner", "mimic", "money", "mount",
    "nerve", "night", "ninja", "noble", "north",
    "ocean", "ombre", "omega", "orbit", "order",
    "pearl", "phase", "pixel", "plant", "plume",
    "point", "power", "pride", "prime", "prize",
    "proof", "prism", "pulse", "punch",
    "queen", "quest",
    "racer", "radar", "reign", "rider", "risen", "river",
    "robin", "royal", "rogue", "raven",
    "saint", "sabre", "scale", "scare", "scene", "score",
    "scout", "shade", "shark", "sharp", "shell", "shift",
    "shire", "sight", "sigma", "siren", "skill", "skull",
    "sleek", "slick", "sling", "smart", "smite", "smoke",
    "snake", "solar", "solid", "sonic", "south", "space",
    "spark", "spear", "speed", "spell", "spice", "spire",
    "spite", "staff", "stage", "stake", "stand", "steam",
    "steel", "stern", "steed", "sting", "stone", "storm",
    "story", "stray", "surge", "swamp", "swift", "sword",
    "talon", "thorn", "tiger", "titan", "token", "torch",
    "totem", "tower", "toxic", "trace", "trade", "trail",
    "tribe", "trick", "troop", "truck", "trump", "trust",
    "truth", "tulip", "twist",
    "ultra", "unity", "upper",
    "valor", "vault", "vigor", "viper", "virus", "voice",
    "watch", "whale", "wheat", "wheel", "witch", "world",
    "wrath", "youth",
    "anchor", "arcane", "arctic", "badger", "bandit",
    "bishop", "blitz", "bonfire",
    "cactus", "canary", "cipher", "cobalt",
    "cosmic", "dragon", "falcon", "fusion",
    "hunter", "impact", "jungle", "knight",
    "legend", "magnet", "matrix",
    "master", "mystic", "oracle", "pirate", "prince",
    "python", "random", "ranger", "raptor", "rascal", "raven",
    "reaper", "rocket", "runner", "rustic", "sacred", "savage",
    "scarab", "shadow", "sniper",
    "spirit", "strike", "sunset",
    "temple", "thunder", "titan", "turbo", "undead",
    "venom", "viking", "vortex", "warrior", "wizard", "wraith",
    "zenith", "zombie",
]


def load_words_from_file(filepath):
    words = []
    with open(filepath, "r", encoding="utf-8") as f:
        for line in f:
            word = line.strip()
            if word and not word.startswith("#"):
                words.append(word)
    return words


def _get_default_wordlist_path():
    import sys
    from pathlib import Path
    base = Path(getattr(sys, '_MEIPASS', Path(__file__).parent.parent))
    wl = base / "wordlist_3000.txt"
    if wl.exists():
        return str(wl)
    return None


def get_valid_words(min_length=3, max_length=0, custom_words=None, wordlist_file=None):
    if wordlist_file:
        words = load_words_from_file(wordlist_file)
    else:
        default_path = _get_default_wordlist_path()
        if default_path:
            words = load_words_from_file(default_path)
        else:
            words = list(COOL_WORDS)
    if custom_words:
        words = words + custom_words
    valid = set()
    for word in words:
        if all(c in BASE58_CHARS for c in word) and len(word) >= min_length:
            if max_length > 0 and len(word) > max_length:
                continue
            valid.add(word)
    return sorted(valid, key=lambda w: (-len(w), w))
