BASE58_CHARS = set("123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz")
UPPERCASE_BASE58 = set("ABCDEFGHJKLMNPQRSTUVWXYZ")

COOL_WORDS = [
    "ace", "ape", "arc", "art", "axe",
    "bad", "bag", "ban", "bar", "bat", "bay", "bed", "bet", "big", "bit",
    "bob", "bog", "bot", "bow", "box", "boy", "bud", "bug", "bum", "bun",
    "bus", "but", "buy",
    "cab", "cad", "cam", "can", "cap", "car", "cat", "cop", "cow", "cry",
    "cub", "cud", "cup", "cur", "cut",
    "dab", "dad", "dam", "day", "den", "dew", "did", "dig", "dim", "dip",
    "doc", "dog", "don", "dot", "dry", "dub", "dud", "dug", "dun", "duo",
    "dye",
    "ear", "eat", "eel", "egg", "ego", "end", "era", "eve", "ewe", "eye",
    "fab", "fad", "fan", "far", "fat", "fax", "fed", "fee", "fen", "few",
    "fig", "fin", "fir", "fit", "fix", "fly", "foe", "fog", "fop", "for",
    "fox", "fry", "fun", "fur",
    "gab", "gag", "gap", "gas", "gay", "gem", "get", "gig",
    "gin", "gnu", "god", "got", "gum", "gun", "gut", "guy", "gym",
    "had", "hag", "ham", "has", "hat", "hay", "hen", "her", "hew", "hex",
    "hid", "him", "hip", "his", "hit", "hob", "hod", "hog", "hop", "hot",
    "how", "hub", "hue", "hug", "hum", "hut",
    "ice", "icy", "imp", "ink", "inn", "ion", "ire", "irk", "ivy",
    "jab", "jag", "jam", "jar", "jaw", "jay", "jet", "jig", "job", "jog",
    "jot", "joy", "jug", "jut",
    "keg", "ken", "key", "kid", "kin", "kit",
    "lab", "lad", "lag", "lap", "law", "lay", "lea", "led", "leg", "let",
    "lid", "lip", "lit", "log", "lot", "low", "lug",
    "mad", "man", "map", "mar", "mat", "maw", "max", "may", "men", "met",
    "mid", "mix", "mob", "mod", "mom", "mop", "mow", "mud", "mug", "mum",
    "nab", "nag", "nap", "net", "new", "nip", "nit", "nod", "nor",
    "not", "now", "nub", "nun", "nut",
    "oak", "oar", "oat", "odd", "ode", "off", "oft", "ohm",
    "one", "opt", "orb", "ore", "our", "out", "owe", "own",
    "pad", "pan", "pap", "par", "pat", "paw", "pay", "pea",
    "peg", "pen", "pep", "per", "pet", "pew", "pie", "pig", "pin", "pit",
    "ply", "pod", "pop", "pot", "pow", "pro", "pry", "pub", "pug", "pun",
    "pup", "pus", "put",
    "rag", "ram", "ran", "rap", "rat", "raw", "ray", "red", "ref", "rib",
    "rid", "rig", "rim", "rip", "rob", "rod", "roe", "rot", "row", "rub",
    "rug", "rum", "run", "rut", "rye",
    "sac", "sad", "sag", "sap", "sat", "saw", "say", "sea", "set", "sew",
    "shy", "sin", "sip", "sir", "sis", "sit", "six", "ski", "sky", "sly",
    "sob", "sod", "son", "sop", "sot", "sow", "soy", "spa", "spy", "sty",
    "sub", "sue", "sum", "sun", "sup",
    "tab", "tad", "tag", "tan", "tap", "tar", "tat", "tax", "tea", "ten",
    "the", "thy", "tic", "tie", "tin", "tip", "toe", "ton", "too", "top",
    "tot", "tow", "toy", "try", "tub", "tug", "tun", "two",
    "ugh", "urn", "use",
    "van", "vat", "vet", "vex", "via", "vie", "vim", "vow",
    "wad", "wag", "war", "was", "wax", "way", "web", "wed", "wet", "who",
    "why", "wig", "win", "wit", "woe", "wok", "won", "woo", "wow",
    "yak", "yam", "yap", "yaw", "yea", "yes", "yet", "yew", "yin", "you",
    "yow",
    "zap", "zed", "zen", "zig", "zip", "zit", "zoo",
    "able", "acid", "aged", "area", "army", "auto", "away",
    "baby", "back", "bake", "band", "bang", "bank", "bare",
    "barn", "base", "bass", "bath", "bead", "beam", "bean", "bear", "beat",
    "beef", "been", "beer", "bend", "bent", "best", "bike",
    "bird", "bite", "blow", "blur", "boar", "boat", "body", "bond",
    "bone", "book", "boom", "boot", "bore", "born",
    "boss", "both", "buck", "buff", "bump",
    "burn", "bust", "busy", "buzz",
    "cafe", "cage", "cake", "came", "camp", "cape", "card", "care",
    "cart", "case", "cash", "cast", "cave", "chad", "chef", "chin",
    "chip", "chop", "cite", "city", "clad", "clam", "clap", "claw",
    "clay", "clip", "club", "clue", "coat", "cock", "code",
    "coin", "comb", "come", "cook", "cope",
    "copy", "cord", "core", "cork", "corn", "cost", "cozy", "crab", "crew",
    "crop", "crow", "cube", "cure", "cute",
    "damp", "dare", "dark", "dart", "dash", "data", "dawn", "days", "dead",
    "deaf", "dear", "debt", "deck", "deed", "deem", "deep", "deer",
    "demo", "deny", "desk", "dice", "died", "diet", "dine", "dirt",
    "dish", "disk", "dock", "does", "dome", "done", "doom", "door", "dose",
    "dove", "down", "drag", "draw", "drew", "drip", "drop", "drug", "drum",
    "duck", "dude", "dumb", "dump", "dune",
    "dunk", "dusk", "dust", "duty",
    "each", "earn", "ease", "east", "easy", "edge", "edit",
    "emit", "ends", "epic", "even", "ever", "exam", "exec", "exit",
    "eyed", "eyes",
    "face", "fact", "fade", "fair", "fake", "fame", "fang",
    "fare", "farm", "fast", "fate", "fawn", "fear", "feat", "feed",
    "feet", "fine", "fire",
    "firm", "fish", "fist", "five", "flag", "flat", "flaw", "fled", "flew",
    "flip", "flog", "foam", "fond", "food",
    "foot", "ford", "fore", "fork", "form", "fort", "four",
    "free", "frog", "from", "fury", "fuse", "fuss",
    "game", "gang", "gape", "garb", "gate", "gave", "gaze",
    "gear", "gene", "gift", "gist", "give", "glad",
    "glee", "glow", "goat", "goes", "grab", "gram", "gray", "grew", "grid", "grim",
    "grin", "grip", "grit", "grow", "guru", "gust",
    "hack", "hair", "hand", "hang",
    "hard", "hare", "harm", "harp", "hash", "hate",
    "hawk", "haze", "hazy", "head", "heap", "hear", "heat", "heed",
    "hero", "hide",
    "high", "hike", "hint", "hire", "hiss", "hive",
    "hoax", "hope",
    "horn", "hose", "host", "hour", "huge",
    "hunt", "hurt", "hush", "hymn",
    "icon", "idea",
    "jack", "jade", "jazz", "jerk", "jest", "jobs", "john", "join",
    "joke", "jump", "jury", "just",
    "keen", "keep", "kept", "kick", "kids", "kind", "king", "kiss",
    "kite", "knee", "knew", "knit", "knob", "knot", "know",
    "lace", "lack", "lady", "lake", "lame", "lamp", "land",
    "lane", "lark", "lash", "lass", "last", "late", "lawn", "lazy", "lead",
    "leak", "lean", "leap", "lend", "lens", "less",
    "liar", "lice", "lick", "lied", "limb", "lime",
    "limp", "line", "link", "lion", "list", "live", "loan",
    "lock", "loft", "lone", "long", "look", "loop", "lord", "lore",
    "lose", "loss", "lost", "loud", "love", "luck", "lump", "lung",
    "lure", "lurk", "lush", "lust",
    "mace", "made", "mage", "magi", "maid", "main", "make",
    "mane", "many", "mare", "mark", "mars", "mash", "mask",
    "mass", "mast", "mate", "math", "maze", "mead", "mean", "meat",
    "meek", "mend", "menu", "mere", "mesh", "mess",
    "mine", "mint", "miss",
    "mist", "mite", "moat", "mock", "mode", "monk",
    "mood", "moon", "moor", "more", "moss", "most", "moth", "move", "much",
    "muse", "mush", "musk", "must", "mute", "myth",
    "name", "nape", "nave", "navy", "near", "neat", "neck", "need",
    "nest", "news", "next", "nice", "nine", "node", "none", "noon", "norm",
    "nose", "note", "noun", "nude",
    "oath", "obey", "odds", "omen", "once", "onto",
    "open", "orca", "oven", "over", "owed",
    "pace", "pack", "pact", "page", "paid", "pain", "pair",
    "pane", "pang", "park", "part", "pass", "past", "path", "pave",
    "peak", "pear", "peat", "perk", "pest", "pick",
    "pier", "pine", "pink", "pipe", "plan", "play", "plea",
    "plot", "plow", "ploy", "plug", "plum", "plus", "poem", "poet",
    "pond", "pony", "poor", "pope", "pork", "port",
    "pose", "post", "pour", "pray", "prey", "prop", "pump",
    "punk", "pure", "push",
    "race", "rack", "raft", "rage", "raid", "rain", "rake", "ramp",
    "rang", "rank", "rare", "rash", "rate", "rave", "rays", "read",
    "reap", "rear", "reef", "rein", "rent", "rest", "rice",
    "rich", "ride", "rift", "ring", "riot", "rise", "risk", "road", "roam",
    "roar", "robe", "rock", "rode", "root",
    "rope", "rose", "rude", "ruin", "rump", "rung", "rush", "rust",
    "safe", "sage", "said", "sake", "sand",
    "sane", "sang", "sank", "save", "scan", "scar", "seed",
    "seek", "seem", "seen", "send", "sent", "shed", "shin",
    "ship", "shoe", "shop", "shot", "show", "shut", "sick", "side", "sigh",
    "sign", "sing", "sink", "site", "size", "skin", "skip",
    "slab", "slam", "slap", "sled", "slew", "slid", "slim", "slip", "slit",
    "slow", "slug", "snap", "snip", "snow", "snub", "soak", "soar",
    "sock", "soft", "sold", "some", "song", "soon",
    "sore", "sort", "sour", "span", "spar", "spec", "sped", "spin",
    "spit", "spot", "spur", "stab", "star", "stay", "stem", "step", "stew",
    "stir", "stop", "stub", "stud", "stun", "such", "suit", "sung",
    "sunk", "sure", "surf", "swan", "swap", "swim",
    "tack", "tact", "tank", "tape", "taps", "task", "team", "tear", "teen",
    "tend", "tent", "term", "test", "text", "than", "that", "them", "then", "they",
    "thin", "this", "thou", "thud", "thus", "tick", "tide", "tidy", "tied",
    "tier", "tiny", "tire", "toad",
    "tone", "took", "tops", "tore", "torn",
    "toss", "tour", "town", "trap", "tray", "tree", "trek", "trim", "trio",
    "trip", "trod", "trot", "true", "tuck", "tuna", "tune", "turf", "turn",
    "twin", "type",
    "ugly", "undo", "unit", "unto", "upon", "urge", "used", "user",
    "vain", "vane", "vary", "vase", "vast", "vein", "vent",
    "verb", "very", "vest", "veto", "vibe", "vice", "view", "vine", "visa",
    "void", "vote",
    "wade", "wage", "wait", "wake", "want",
    "ward", "warm", "warn", "warp", "wart", "wary", "wash", "wasp", "wave",
    "wavy", "waxy", "weak", "wean", "wear", "weed", "week", "went",
    "were", "west", "what", "when", "whim", "whip", "whom", "wick", "wide",
    "wind", "wine", "wing",
    "wink", "wipe", "wire", "wise", "wish", "wisp", "with", "woke",
    "womb", "wood", "word", "wore", "work", "worm", "worn", "wove",
    "wrap", "wren",
    "yank", "yard", "yarn", "year", "yoga", "yoke", "your",
    "zero", "zest", "zinc", "zone", "zoom",
    "angel", "arena", "beast", "blade", "blaze", "bloom",
    "brain", "brave", "bravo", "break", "bride", "bring", "brisk", "broad",
    "brook", "brush", "burst",
    "candy", "cargo", "cedar", "chain", "chair", "champ", "chaos",
    "charm", "chase", "cheap", "check", "chess", "chief", "claim",
    "clash", "class", "clean", "climb", "cling", "clone",
    "close", "cloud", "coach", "coral", "could", "count", "court", "cover",
    "crack", "craft", "crane", "crash", "cream", "creek", "crest", "crisp",
    "cross", "crowd", "crown", "crush", "curve", "cyber",
    "dance", "death", "demon", "dodge", "donor", "doubt",
    "draft", "drain", "drake", "drama", "dream", "dress", "drift",
    "drink", "drive", "drone", "dwarf",
    "earth", "ember", "ended", "enter", "equip",
    "erase", "error", "event", "every", "exact", "extra",
    "fable", "faith", "fault", "feast", "fiber", "fiend", "fight",
    "flame", "flash", "fleet", "flesh", "float", "flock", "flood",
    "flora", "fluid", "flute", "focal", "force", "forge",
    "forty", "found", "frame", "frank", "fraud", "fresh", "front", "frost",
    "fruit", "funny",
    "gamer", "gamma", "ghost", "giant", "given", "gnome", "grace",
    "grade", "grain", "grand", "grant", "graph", "grasp", "grass", "grave",
    "great", "greed", "green", "grief", "grind", "groan", "groom", "gross",
    "group", "grove", "guard", "guess", "guide",
    "lunar",
    "magic", "major", "manor", "march", "marsh", "mason", "match",
    "maxim", "mayor", "mercy", "merge", "merit",
    "might", "miner", "minor", "money", "month", "moose", "mount",
    "mouse", "music",
    "nerve", "never", "night", "ninja", "noise", "north", "noted",
    "nymph",
    "ocean", "offer", "omega", "onset", "opera", "orbit", "order", "other",
    "outer", "oxide", "ozone",
    "panda", "panic", "paper", "patch", "pause", "peace", "phase",
    "piano", "point", "power", "press", "price",
    "pride", "prime", "print", "prize", "probe",
    "proof", "proud", "proxy", "purge", "queen",
    "quest", "quick", "quiet",
    "radar", "radio", "raise", "ranch", "range", "rapid", "raven",
    "reach", "realm", "reign", "rider", "ridge", "rigid",
    "river", "robin", "robot", "rocky", "rogue", "roman", "roost", "royal",
    "ruler", "rural",
    "saber", "saint", "scene", "scope", "score",
    "scout", "shade", "shake", "shame", "shape", "share", "shark",
    "sharp", "sheer", "shift", "shire", "shock",
    "shore", "short", "shout", "sigma", "sight", "siege", "since",
    "slash", "slate", "sleek", "slice", "slide", "slime", "slope", "smart",
    "smile", "smith", "smoke", "snake", "sonic", "south", "space", "spare",
    "spark", "speak", "spear",
    "speed", "spend", "spice", "spike", "spine", "spite", "split",
    "spoke", "spore", "sport", "spray", "squad", "stack", "staff", "stage",
    "stain", "stake", "stand", "stare", "stark", "start",
    "state", "stead", "steam", "steep", "steer", "stern",
    "stick", "stiff", "sting", "stock", "stoic", "stone", "stood",
    "storm", "story", "stout", "stove", "strap", "straw", "stray",
    "strip", "stuck", "study", "stuff", "stump", "stung", "stunt", "style",
    "sugar", "surge", "swamp", "swarm", "swear", "sweep", "sweet", "swift",
    "swing", "sworn", "sword",
    "taste", "teach", "theme", "thick", "thing", "think", "thorn",
    "those", "three", "throw", "thumb", "tiger", "tight", "timer", "titan",
    "toast", "token", "torch", "touch", "tough", "tower",
    "toxic", "trace", "track", "trade", "trait", "treat",
    "trend", "trick", "troop", "trout", "truck", "truly",
    "trump", "trunk", "trust", "truth", "turbo",
    "twist",
    "under", "union", "unite", "unity", "upper", "upset", "urban",
    "usher", "utter",
    "vapor", "vault", "vigor", "viral", "viper", "vivid",
    "vocal", "voice", "vortex",
    "watch", "water", "weary", "wheat", "where", "which",
    "whirl", "white", "whose", "witch", "woman", "world",
    "worth", "would", "wound", "wrath", "write",
    "yacht", "young", "youth",
    "sol", "luna", "degen", "moon", "pump", "wagmi", "gwei",
    "nft", "dao", "dex", "rug", "ape", "gem", "chad", "based",
    "whale", "sigma", "omega", "theta",
    "crypto", "dragon", "energy", "falcon", "hunter", "knight", "legend",
    "master", "mystic", "oracle", "pirate", "prince",
    "python", "random", "ranger", "raptor", "rascal", "raven",
    "reaper", "rocket", "runner", "rustic", "sacred", "savage",
    "scarab", "shadow", "sniper",
    "spirit", "strike", "sunset",
    "temple", "thunder", "titan", "turbo", "undead",
    "venom", "viking", "vortex", "warrior", "wizard", "wraith",
    "zenith", "zombie",
]


def get_valid_words(min_length=3, max_length=0, custom_words=None):
    words = list(COOL_WORDS)
    if custom_words:
        words = words + custom_words
    valid = set()
    for word in words:
        if all(c in BASE58_CHARS for c in word) and len(word) >= min_length:
            if max_length > 0 and len(word) > max_length:
                continue
            valid.add(word)
    return sorted(valid, key=lambda w: (-len(w), w))
