COOL_WORDS = [
    "ace", "ape", "arc", "art", "axe",
    "bad", "bag", "ban", "bar", "bat", "bay", "bed", "bet", "big", "bit",
    "bob", "bog", "bot", "bow", "box", "boy", "bud", "bug", "bum", "bun",
    "bus", "but", "buy",
    "cab", "cad", "cam", "can", "cap", "car", "cat", "cop", "cow", "cry",
    "cub", "cud", "cup", "cur", "cut",
    "dab", "dad", "dam", "day", "den", "dew", "did", "dig", "dim", "dip",
    "doc", "dog", "don", "dot", "dry", "dub", "dud", "dug", "dun", "duo",
    "dye",
    "ear", "eat", "eel", "egg", "ego", "elm", "emu", "end", "era", "eve",
    "ewe", "eye",
    "fab", "fad", "fan", "far", "fat", "fax", "fed", "fee", "fen", "few",
    "fig", "fin", "fir", "fit", "fix", "fly", "foe", "fog", "fop", "for",
    "fox", "fry", "fun", "fur",
    "gab", "gag", "gal", "gap", "gas", "gay", "gel", "gem", "get", "gig",
    "gin", "gnu", "god", "got", "gum", "gun", "gut", "guy", "gym",
    "had", "hag", "ham", "has", "hat", "hay", "hen", "her", "hew", "hex",
    "hid", "him", "hip", "his", "hit", "hob", "hod", "hog", "hop", "hot",
    "how", "hub", "hue", "hug", "hum", "hut",
    "ice", "icy", "ill", "imp", "ink", "inn", "ion", "ire", "irk", "ivy",
    "jab", "jag", "jam", "jar", "jaw", "jay", "jet", "jig", "job", "jog",
    "jot", "joy", "jug", "jut",
    "keg", "ken", "key", "kid", "kin", "kit",
    "lab", "lad", "lag", "lap", "law", "lay", "lea", "led", "leg", "let",
    "lid", "lip", "lit", "log", "lot", "low", "lug",
    "mad", "man", "map", "mar", "mat", "maw", "max", "may", "men", "met",
    "mid", "mix", "mob", "mod", "mom", "mop", "mow", "mud", "mug", "mum",
    "nab", "nag", "nap", "net", "new", "nil", "nip", "nit", "nod", "nor",
    "not", "now", "nub", "nun", "nut",
    "oak", "oar", "oat", "odd", "ode", "off", "oft", "ohm", "oil", "old",
    "one", "opt", "orb", "ore", "our", "out", "owe", "owl", "own",
    "ace", "pad", "pal", "pan", "pap", "par", "pat", "paw", "pay", "pea",
    "peg", "pen", "pep", "per", "pet", "pew", "pie", "pig", "pin", "pit",
    "ply", "pod", "pop", "pot", "pow", "pro", "pry", "pub", "pug", "pun",
    "pup", "pus", "put",
    "rag", "ram", "ran", "rap", "rat", "raw", "ray", "red", "ref", "rib",
    "rid", "rig", "rim", "rip", "rob", "rod", "roe", "rot", "row", "rub",
    "rug", "rum", "run", "rut", "rye",
    "sac", "sad", "sag", "sap", "sat", "saw", "say", "sea", "set", "sew",
    "shy", "sin", "sip", "sir", "sis", "sit", "six", "ski", "sky", "sly",
    "sob", "sod", "son", "sop", "sot", "sow", "soy", "spa", "spy", "sty",
    "sub", "sue", "sum", "sun", "sup",
    "tab", "tad", "tag", "tan", "tap", "tar", "tat", "tax", "tea", "ten",
    "the", "thy", "tic", "tie", "tin", "tip", "toe", "ton", "too", "top",
    "tot", "tow", "toy", "try", "tub", "tug", "tun", "two",
    "ugh", "urn", "use",
    "van", "vat", "vet", "vex", "via", "vie", "vim", "vow",
    "wad", "wag", "war", "was", "wax", "way", "web", "wed", "wet", "who",
    "why", "wig", "win", "wit", "woe", "wok", "won", "woo", "wow",
    "yak", "yam", "yap", "yaw", "yea", "yes", "yet", "yew", "yin", "you",
    "yow",
    "zap", "zed", "zen", "zig", "zip", "zit", "zoo",
    "able", "acid", "aged", "also", "area", "army", "auto", "away",
    "baby", "back", "bake", "bald", "ball", "band", "bang", "bank", "bare",
    "barn", "base", "bass", "bath", "bead", "beam", "bean", "bear", "beat",
    "beef", "been", "beer", "bell", "belt", "bend", "bent", "best", "bike",
    "bird", "bite", "blow", "blue", "blur", "boar", "boat", "body", "bold",
    "bolt", "bomb", "bond", "bone", "book", "boom", "boot", "bore", "born",
    "boss", "both", "bowl", "buck", "buff", "bulb", "bulk", "bull", "bump",
    "burn", "bust", "busy", "buzz",
    "cafe", "cage", "cake", "calm", "came", "camp", "cape", "card", "care",
    "cart", "case", "cash", "cast", "cave", "cell", "chad", "chef", "chin",
    "chip", "chop", "cite", "city", "clad", "clam", "clan", "clap", "claw",
    "clay", "clip", "club", "clue", "coal", "coat", "cock", "code", "coil",
    "coin", "cold", "cole", "colt", "comb", "come", "cook", "cool", "cope",
    "copy", "cord", "core", "cork", "corn", "cost", "cozy", "crab", "crew",
    "crop", "crow", "cube", "cult", "cure", "curl", "cute",
    "damp", "dare", "dark", "dart", "dash", "data", "dawn", "days", "dead",
    "deaf", "deal", "dear", "debt", "deck", "deed", "deem", "deep", "deer",
    "demo", "deny", "desk", "dial", "dice", "died", "diet", "dine", "dirt",
    "dish", "disk", "dock", "does", "dome", "done", "doom", "door", "dose",
    "dove", "down", "drag", "draw", "drew", "drip", "drop", "drug", "drum",
    "dual", "duck", "dude", "duel", "duke", "dull", "dumb", "dump", "dune",
    "dunk", "dusk", "dust", "duty",
    "each", "earl", "earn", "ease", "east", "easy", "edge", "edit", "else",
    "emit", "ends", "epic", "even", "ever", "evil", "exam", "exec", "exit",
    "eyed", "eyes",
    "face", "fact", "fade", "fail", "fair", "fake", "fall", "fame", "fang",
    "fare", "farm", "fast", "fate", "fawn", "fear", "feat", "feed", "feel",
    "feet", "fell", "felt", "file", "fill", "film", "find", "fine", "fire",
    "firm", "fish", "fist", "five", "flag", "flat", "flaw", "fled", "flew",
    "flip", "flog", "flow", "foam", "foil", "fold", "folk", "fond", "food",
    "fool", "foot", "ford", "fore", "fork", "form", "fort", "foul", "four",
    "free", "frog", "from", "fuel", "full", "fund", "fury", "fuse", "fuss",
    "gait", "gale", "game", "gang", "gape", "garb", "gate", "gave", "gaze",
    "gear", "gene", "gift", "gild", "gilt", "girl", "gist", "give", "glad",
    "glee", "glen", "glow", "glue", "glum", "goat", "goes", "gold", "golf",
    "gone", "good", "gore", "grab", "gram", "gray", "grew", "grid", "grim",
    "grin", "grip", "grit", "grow", "gulf", "guru", "gust",
    "hack", "hail", "hair", "hale", "half", "hall", "halt", "hand", "hang",
    "hard", "hare", "harm", "harp", "hash", "haste", "hate", "haul", "have",
    "hawk", "haze", "hazy", "head", "heal", "heap", "hear", "heat", "heed",
    "heel", "held", "helm", "help", "herb", "herd", "here", "hero", "hide",
    "high", "hike", "hill", "hilt", "hind", "hint", "hire", "hiss", "hive",
    "hoax", "hold", "hole", "holy", "home", "hone", "hood", "hook", "hope",
    "horn", "hose", "host", "hour", "howl", "huge", "hull", "hump", "hung",
    "hunt", "hurl", "hurt", "hush", "hymn",
    "icon", "idea", "idle", "idol",
    "jack", "jade", "jail", "jazz", "jerk", "jest", "jobs", "john", "join",
    "joke", "jolt", "jump", "jungle", "jury", "just",
    "keen", "keep", "kept", "kick", "kids", "kill", "kind", "king", "kiss",
    "kite", "knee", "knew", "knit", "knob", "knot", "know",
    "lace", "lack", "lady", "laid", "lake", "lamb", "lame", "lamp", "land",
    "lane", "lark", "lash", "lass", "last", "late", "lawn", "lazy", "lead",
    "leaf", "leak", "lean", "leap", "left", "lend", "lens", "less", "levy",
    "liar", "lice", "lick", "lied", "life", "lift", "like", "limb", "lime",
    "limp", "line", "link", "lion", "list", "live", "load", "loaf", "loan",
    "lock", "loft", "logo", "lone", "long", "look", "loop", "lord", "lore",
    "lose", "loss", "lost", "loud", "love", "luck", "lull", "lump", "lung",
    "lure", "lurk", "lush", "lust",
    "mace", "made", "mage", "magi", "maid", "mail", "main", "make", "male",
    "mall", "malt", "mane", "many", "mare", "mark", "mars", "mash", "mask",
    "mass", "mast", "mate", "math", "maze", "mead", "meal", "mean", "meat",
    "meek", "meld", "melt", "memo", "mend", "menu", "mere", "mesh", "mess",
    "mild", "mile", "milk", "mill", "mime", "mind", "mine", "mint", "miss",
    "mist", "mite", "moat", "mock", "mode", "mold", "mole", "molt", "monk",
    "mood", "moon", "moor", "more", "moss", "most", "moth", "move", "much",
    "mule", "muse", "mush", "musk", "must", "mute", "myth",
    "nail", "name", "nape", "nave", "navy", "near", "neat", "neck", "need",
    "nest", "news", "next", "nice", "nine", "node", "none", "noon", "norm",
    "nose", "note", "noun", "nude",
    "oath", "obey", "odds", "oink", "okay", "omen", "once", "only", "onto",
    "opal", "open", "oral", "orca", "oven", "over", "owed",
    "pace", "pack", "pact", "page", "paid", "pail", "pain", "pair", "pale",
    "palm", "pane", "pang", "park", "part", "pass", "past", "path", "pave",
    "peak", "pear", "peat", "peel", "peer", "pelt", "perk", "pest", "pick",
    "pier", "pile", "pill", "pine", "pink", "pipe", "plan", "play", "plea",
    "plot", "plow", "ploy", "plug", "plum", "plus", "poem", "poet", "pole",
    "poll", "polo", "pond", "pony", "pool", "poor", "pope", "pork", "port",
    "pose", "post", "pour", "pray", "prey", "prop", "pull", "pulp", "pump",
    "punk", "pure", "push",
    "race", "rack", "raft", "rage", "raid", "rail", "rain", "rake", "ramp",
    "rang", "rank", "rare", "rash", "rate", "rave", "rays", "read", "real",
    "reap", "rear", "reef", "reel", "rein", "rely", "rent", "rest", "rice",
    "rich", "ride", "rift", "ring", "riot", "rise", "risk", "road", "roam",
    "roar", "robe", "rock", "rode", "role", "roll", "roof", "room", "root",
    "rope", "rose", "rude", "ruin", "rule", "rump", "rung", "rush", "rust",
    "safe", "sage", "said", "sail", "sake", "sale", "salt", "same", "sand",
    "sane", "sang", "sank", "save", "scan", "scar", "seal", "seam", "seed",
    "seek", "seem", "seen", "self", "sell", "send", "sent", "shed", "shin",
    "ship", "shoe", "shop", "shot", "show", "shut", "sick", "side", "sigh",
    "sign", "silk", "sill", "sing", "sink", "site", "size", "skin", "skip",
    "slab", "slam", "slap", "sled", "slew", "slid", "slim", "slip", "slit",
    "slot", "slow", "slug", "snap", "snip", "snow", "snub", "soak", "soar",
    "sock", "soft", "soil", "sold", "sole", "solo", "some", "song", "soon",
    "sore", "sort", "soul", "sour", "span", "spar", "spec", "sped", "spin",
    "spit", "spot", "spur", "stab", "star", "stay", "stem", "step", "stew",
    "stir", "stop", "stub", "stud", "stun", "such", "suit", "sulk", "sung",
    "sunk", "sure", "surf", "swan", "swap", "swim",
    "tack", "tact", "tail", "take", "tale", "talk", "tall", "tame", "tang",
    "tank", "tape", "taps", "task", "team", "tear", "teen", "tell", "tend",
    "tent", "term", "test", "text", "than", "that", "them", "then", "they",
    "thin", "this", "thou", "thud", "thus", "tick", "tide", "tidy", "tied",
    "tier", "tile", "till", "tilt", "time", "tiny", "tire", "toad", "toil",
    "told", "toll", "tomb", "tone", "took", "tool", "tops", "tore", "torn",
    "toss", "tour", "town", "trap", "tray", "tree", "trek", "trim", "trio",
    "trip", "trod", "trot", "true", "tuck", "tuna", "tune", "turf", "turn",
    "twin", "type",
    "ugly", "undo", "unit", "unto", "upon", "urge", "used", "user",
    "vain", "vale", "vane", "vary", "vase", "vast", "veil", "vein", "vent",
    "verb", "very", "vest", "veto", "vibe", "vice", "view", "vine", "visa",
    "void", "volt", "vote",
    "wade", "wage", "wail", "wait", "wake", "walk", "wall", "wand", "want",
    "ward", "warm", "warn", "warp", "wart", "wary", "wash", "wasp", "wave",
    "wavy", "waxy", "weak", "wean", "wear", "weed", "week", "well", "went",
    "were", "west", "what", "when", "whim", "whip", "whom", "wick", "wide",
    "wife", "wild", "will", "wilt", "wily", "wimp", "wind", "wine", "wing",
    "wink", "wipe", "wire", "wise", "wish", "wisp", "with", "woke", "wolf",
    "womb", "wood", "wool", "word", "wore", "work", "worm", "worn", "wove",
    "wrap", "wren",
    "yank", "yard", "yarn", "year", "yell", "yoga", "yoke", "your",
    "zeal", "zero", "zest", "zinc", "zone", "zoom",
    "alpha", "angel", "atlas", "arena", "blaze", "beast", "blade", "bloom",
    "brain", "brave", "bravo", "break", "bride", "bring", "brisk", "broad",
    "brook", "brush", "build", "burst",
    "cabal", "candy", "cargo", "cedar", "chain", "chair", "champ", "chaos",
    "charm", "chase", "cheap", "check", "chess", "chief", "chill", "claim",
    "clash", "class", "clean", "clear", "climb", "cling", "clock", "clone",
    "close", "cloud", "coach", "coral", "could", "count", "court", "cover",
    "crack", "craft", "crane", "crash", "cream", "creek", "crest", "crisp",
    "cross", "crowd", "crown", "crush", "curve", "cyber",
    "dance", "death", "demon", "devil", "divine", "dodge", "donor", "doubt",
    "draft", "drain", "drake", "drama", "dream", "dress", "drift", "drill",
    "drink", "drive", "drone", "dwarf",
    "eagle", "earth", "elite", "ember", "ended", "enter", "equal", "equip",
    "erase", "error", "event", "every", "exact", "exile", "extra",
    "fable", "faith", "fault", "feast", "fiber", "field", "fiend", "fight",
    "final", "flame", "flash", "fleet", "flesh", "float", "flock", "flood",
    "floor", "flora", "flour", "fluid", "flute", "focal", "force", "forge",
    "forty", "found", "frame", "frank", "fraud", "fresh", "front", "frost",
    "fruit", "funny",
    "gamma", "gamer", "ghost", "giant", "given", "gland", "glass", "gleam",
    "glide", "globe", "gloom", "glory", "glyph", "gnome", "golem", "grace",
    "grade", "grain", "grand", "grant", "graph", "grasp", "grass", "grave",
    "great", "greed", "green", "grief", "grind", "groan", "groom", "gross",
    "group", "grove", "growl", "guard", "guess", "guide", "guild", "guise",
    "lunar", "lyric",
    "magic", "major", "manor", "maple", "march", "marsh", "mason", "match",
    "maxim", "mayor", "medal", "mercy", "merge", "merit", "metal", "might",
    "miner", "minor", "model", "money", "month", "moose", "moral", "mount",
    "mouse", "music", "myth",
    "nerve", "never", "night", "ninja", "noble", "noise", "north", "noted",
    "novel", "nymph",
    "ocean", "offer", "omega", "onset", "opera", "orbit", "order", "other",
    "outer", "oxide", "ozone",
    "panda", "panic", "paper", "patch", "pause", "peace", "pearl", "phase",
    "piano", "pilot", "pixel", "place", "plain", "plane", "plant", "plate",
    "plaza", "plead", "pluck", "plumb", "plume", "plump", "point", "polar",
    "power", "press", "price", "pride", "prime", "print", "prize", "probe",
    "proof", "proud", "proxy", "pulse", "punch", "pupil", "purge", "queen",
    "quest", "quick", "quiet", "quilt", "quota", "quote",
    "radar", "radio", "raise", "rally", "ranch", "range", "rapid", "raven",
    "reach", "realm", "rebel", "reign", "rider", "ridge", "rifle", "rigid",
    "river", "robin", "robot", "rocky", "rogue", "roman", "roost", "royal",
    "ruler", "rural",
    "saber", "saint", "salad", "scale", "scare", "scene", "scope", "score",
    "scout", "shade", "shake", "shall", "shame", "shape", "share", "shark",
    "sharp", "sheep", "sheer", "shelf", "shell", "shift", "shire", "shock",
    "shore", "short", "shout", "sigma", "sight", "siege", "since", "skull",
    "slash", "slate", "sleek", "slice", "slide", "slime", "slope", "smart",
    "smell", "smile", "smith", "smoke", "snail", "snake", "solar", "solid",
    "solve", "sonic", "south", "space", "spare", "spark", "speak", "spear",
    "speed", "spell", "spend", "spice", "spike", "spine", "spite", "split",
    "spoke", "spore", "sport", "spray", "squad", "stack", "staff", "stage",
    "stain", "stake", "stale", "stall", "stand", "stare", "stark", "start",
    "state", "stead", "steal", "steam", "steel", "steep", "steer", "stern",
    "stick", "stiff", "still", "sting", "stock", "stoic", "stone", "stood",
    "stool", "storm", "story", "stout", "stove", "strap", "straw", "stray",
    "strip", "stuck", "study", "stuff", "stump", "stung", "stunt", "style",
    "sugar", "surge", "swamp", "swarm", "swear", "sweep", "sweet", "swift",
    "swing", "sworn", "sword",
    "table", "taste", "teach", "theme", "thick", "thing", "think", "thorn",
    "those", "three", "throw", "thumb", "tiger", "tight", "timer", "titan",
    "title", "toast", "token", "torch", "total", "touch", "tough", "tower",
    "toxic", "trace", "track", "trade", "trail", "train", "trait", "treat",
    "trend", "trial", "tribe", "trick", "troop", "trout", "truck", "truly",
    "trump", "trunk", "trust", "truth", "tulip", "tumor", "tunic", "turbo",
    "twist",
    "ultra", "under", "union", "unite", "unity", "upper", "upset", "urban",
    "usher", "usual", "utter",
    "valid", "valor", "valve", "vault", "vigor", "viral", "viper", "vivid",
    "vocal", "voice", "vortex",
    "watch", "water", "weary", "wheat", "wheel", "where", "which", "while",
    "whirl", "white", "whole", "whose", "wield", "witch", "woman", "world",
    "worth", "would", "wound", "wrath", "write",
    "yacht", "yield", "young", "youth",
    "vigor", "zilch",
    "crypto", "defi", "dragon", "energy", "falcon", "galaxy", "golden",
    "hacker", "hunter", "knight", "legend", "master", "mystic", "oracle",
    "panda", "phantom", "pirate", "planet", "plasma", "poison", "prince",
    "python", "racing", "random", "ranger", "raptor", "rascal", "raven",
    "reaper", "rebel", "rocket", "runner", "rustic", "sacred", "savage",
    "scarab", "shadow", "shield", "sigma", "silver", "skull", "sniper",
    "solar", "sorcerer", "spirit", "stealth", "storm", "strike", "sunset",
    "supreme", "temple", "thunder", "titan", "tribal", "turbo", "undead",
    "venom", "viking", "violet", "vortex", "warrior", "wizard", "wraith",
    "zenith", "zombie",
    "sol", "luna", "degen", "moon", "pump", "hodl", "wagmi", "gwei",
    "nft", "dao", "dex", "rug", "ape", "gem", "chad", "based",
    "whale", "alpha", "sigma", "omega", "delta", "gamma", "theta",
    "satoshi", "nakamoto",
]

BASE58_CHARS = set("123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz")

def get_valid_words():
    valid = set()
    for word in COOL_WORDS:
        if all(c in BASE58_CHARS for c in word) and len(word) >= 3:
            valid.add(word)
    return sorted(valid, key=lambda w: (-len(w), w))
